### ISSUE TITLE
xpr file

### ISSUE THREAD

**Issue by NiCoha1408** [Digilent/Zedboard-OLED#3]
if you download the latest zip file and double click on the .xpr file Vivado says: Can't open project 'zedboard-oled'. Please verify that the prjext still exists.

Any help ? 

Thank you.

**Comment by artvvb** [comment]
Double clicking on the XPR requires that Vivado 2018.2 is in your path environment variable. Whether or not this is the case depends on the settings selected during installation, and on whether you have multiple versions installed.

The project can still be opened by launching Vivado and using the Quick Start -> Open Project button, or by running open_project in the TCL Console, passing the path to the XPR.
